### ISSUE TITLE
duplicate arg

### ISSUE THREAD

**Issue by tobozo** [proycon/lingua-cli#1]
hi,

thanks for making that CLI :+1: 

:warning: arg `-d` is duplicate

```
  -d, --minimum-relative-distance <MINIMUM_RELATIVE_DISTANCE>

  -d, --delimiter <DELIMITER>
```

also the default delimiter is a weird nonstandard whitespace

**Comment by proycon** [comment]
On Sat Oct 12, 2024 at 10:35 PM CEST, tobozo wrote:
> :warning: arg `-d` is duplicate
>
> ```
>   -d, --minimum-relative-distance <MINIMUM_RELATIVE_DISTANCE>
>
>   -d, --delimiter <DELIMITER>
> ```

Ah! Thanks for reporting! I fixed it now in 0.4.1

> also the default delimiter is a weird nonstandard whitespace

It's a tab, so the output is simple TSV
